### ISSUE TITLE
Kite plugin inserts weird characters

### ISSUE THREAD

**Issue by geblanco** [kiteco/vim-plugin#214]
Hello!

Trying kite I have encountered various issues.
It inserts weird characters (do not seem to be random), I think is related to the second case in https://github.com/kiteco/vim-plugin/issues/193.
But also, it inserts a concrete sequence of characters, when I try to erase them they are inserted again, and again and again.

Here is a [link with a video](https://imgur.com/a/QoD8bN5) with both phenomena happening. 

Also, here are my configuration details:
OS: Arch Linux
Terminal: Xfce4-Terminal running vim
Vimrc: [Gist](https://github.com/m0n0l0c0/dot_files/blob/desktop/.vimrc)

Best,
Guillermo.

**Comment by airblade** [comment]
Thanks for the video.  It seems suspicious that it keeps inserting `delimitMate`.

Do you still get the problem without the delimitMate plugin installed?

**Comment by m0n0l0c0** [comment]
Yes, it is suspicious, I didn't remember that plugin was installed. Disabling the it removes the problem.  It's a problem because that plugin is really useful, though it's clearly not getting along with kite :(.

Maybe both plugins are accesing the same variables (`completeopt`...)

**Comment by airblade** [comment]
It looks like delimitMate doesn't use `completeopt`.  I think the conflict is over insert-mode mappings.

In your video you can see `delimiteMate#BS()` being inserted.  delimitMate sets up an insert-mode mapping for backspace ([here](https://github.com/Raimondi/delimitMate/blob/728b57a6564c1d2bdfb9b9e0f2f8c5ba3d7e0c5c/plugin/delimitMate.vim#L327-L335)) and somehow the mapping itself is being inserted, not what it resolves to.  I'm not quite sure why.

Kite used to map backspace too until e6bedbf.  The only [insert-mode mappings it sets up](https://github.com/kiteco/vim-plugin/blob/9d5bfd2647f5f3974cd10fa9505c32053bd5603c/autoload/kite.vim#L139-L153) are `<C-e>`, `<C-y>`, `<CR>`, and optionally `<Tab>`.

I'll keep looking into this to work out why delimitMate's mapping is being inserted.  In the meantime we could add it to the plugins to disable (#183) but it shouldn't really be necessary.

**Comment by airblade** [comment]
Please can you try #215?

**Comment by m0n0l0c0** [comment]
Okay, thank you very much for the support!

I'll test it right away and come back here.

**Comment by m0n0l0c0** [comment]
@airblade I've tried it and seems to be broken very badly....

![2019-10-04-104345_1175x968_scrot](https://user-images.githubusercontent.com/6652222/66194078-0ed68980-e694-11e9-876e-44afb46deb0a.png)

I think it enters some bad recursion. It gives me an error, I press enter and gives another error, and so on until the last message depicted in the above photo. Then it exists the error bar, and I am left in selection mode with lots of lines selected.

**Comment by airblade** [comment]
Thanks for trying that branch.  Does this new error vanish if you go back to the master branch?

I can't reproduce this error though somebody else has reported it before.  Are you using tab to accept completion suggestions?

Also, please can you tell me what SHA your kite plugin is at?

**Comment by m0n0l0c0** [comment]
The error does not vanish...
I have the default config for kite, it is deactivated by default, right?
How can I get the SHA of the kite plugin?

**Comment by airblade** [comment]
Well I suppose we have solved the original problem? :)

The vim plugin is activated by default, i.e. it will complete as you type.

To get the SHA, you need to find where the kite vim plugin is installed (you ought to be able to see it in `:scriptnames`), then open the directory in the terminal and `git log -1`.

Alternatively you can do `:echo kite#utils#plugin_version()`.

**Comment by m0n0l0c0** [comment]
Hmmm the problem does not seem to be solved. It's just that it does not come back to the original state.

Right now it does not complete automatically as I type, although I did the following checks:
- kite vim plugin is on master
- `kite_auto_complete`=1
- `delimitMate` is activated

My SHA is 1.0.42

**Comment by m0n0l0c0** [comment]
I have checked and it seems that the `kite_stack` error happens only on split windows inside vim... Is that useful?

**Comment by airblade** [comment]
Aha, that's very useful.  I know what the problem is now.  Thanks!

**Comment by m0n0l0c0** [comment]
Oh, great! :+1:

**Comment by airblade** [comment]
The `b:kite_stack` error should be fixed by #216.

**Comment by m0n0l0c0** [comment]
Yes, it works perfectly, that error is solved! Awesome! :+1:

**Comment by airblade** [comment]
@m0n0l0c0 Great news!  Thanks for confirming.

Is the delimitMate problem still there?

**Comment by m0n0l0c0** [comment]
I don't know, I deactivated it right away. I'll try it tomorrow and come write you back. :)

**Comment by airblade** [comment]
@m0n0l0c0 Ok, sounds good!  Thanks for all the help with this.

**Comment by airblade** [comment]
@m0n0l0c0 I installed [Raimondi/delimitMate](https://github.com/Raimondi/delimitMate) but I can't reproduce the problem (using this plugin's `master` branch).

Please could you give me the exact keystrokes to reproduce the error?

Also, please could you confirm that you do not have deoplete or jedi installed (or any other completion plugin)?

**Comment by m0n0l0c0** [comment]
Hello @airblade,

I have no other completion plugin, and the error still happens, though I cannot get the keystrokes to reproduce the error. I'll try to record it in a macro and send it back to you.

**Comment by m0n0l0c0** [comment]
Hi @airblade,

I've came along another bug in the same fashion. After having the weird characters being inserted in DelimitMate I ended disabling kite :(.

The other day I came across with [Jiangmiao/auto-pairs](https://github.com/jiangmiao/auto-pairs), which does almost the same. Interestingly enough I get the same error as with delimitMate, the function name is being inserted, in this case is [AutoPairsDelete()](https://github.com/jiangmiao/auto-pairs/blob/39f06b873a8449af8ff6a3eee716d3da14d63a76/plugin/auto-pairs.vim#L545). 

What do you think?

**Comment by airblade** [comment]
There was a problem with auto-pairs in #207 but that was fixed by no longer mapping `<BS>`.

Do you see the error only when deleting?  Or perhaps only when the completion menu is open?

**Comment by airblade** [comment]
Hello @m0n0l0c0,

If this problem occurs again, please could you switch on logging with `:let g:kite_log=1` and reproduce the problem?  Hopefully the log file will contain some clues...

**Comment by m0n0l0c0** [comment]
Hello @airblade,

I'm not coding daily for now, but I will surely log all possible information when possible.
Thanks!

**Comment by m0n0l0c0** [comment]
Hello there!

I have a log for you :) [kite-vim.log](https://github.com/kiteco/vim-plugin/files/3984246/kite-vim.log)

I all happened when deleting.
Let me know it any more information is needed.

**Comment by airblade** [comment]
Thank you!

**Comment by AFAgarap** [comment]
> There was a problem with auto-pairs in #207 but that was fixed by no longer mapping `<BS>`.
> 
> Do you see the error only when deleting? Or perhaps only when the completion menu is open?

Hello, I am still having this issue.

**Comment by airblade** [comment]
@AFAgarap Can you give me any clues about how to reproduce this?  I have never been able to reproduce the problem which makes it impossible to fix.

Which plugins do you use?  Is your vim config online?

**Comment by AFAgarap** [comment]
Thank you, @airblade 

I always set up my vim with this simple script I wrote,

```bash
#!/bin/bash

echo "Cloning vim configuration..."
git clone https://github.com/afagarap/vim-config ~/vim-config
git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime

echo "Installing vimrc..."
sh ~/.vim_runtime/install_awesome_vimrc.sh

echo "Installing vim-irblack..."
mkdir -p ~/.vim/bundle
cd ~/.vim/bundle
git clone https://github.com/wesgibbs/vim-irblack

echo "Installing NERDTree..."
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

echo "Installing flake8..."
sudo pip3 install flake8

echo "Finalizing vim configuration setup..."
cp ~/vim-config/vimrc ~/.vimrc

echo "Cleaning up..."
rm -rf ~/vim-config
```

Then, this is my `.vimrc`,

```vim
set runtimepath+=~/.vim_runtime
set number
nnoremap <buffer> <F9> :exec '!python' shellescape(@%, 1)<cr>

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry

autocmd vimenter * NERDTree
autocmd vimenter * wincmd p
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
let NERDTreeMapOpenInTab='<ENTER>'
let NERDTreeMapActivateNode='v'
autocmd BufWinEnter * NERDTreeMirror
colorscheme ir_black

set textwidth=79  " lines longer than 79 columns will be broken
set shiftwidth=4  " operation >> indents 4 columns; << unindents 4 columns
set tabstop=4     " a hard TAB displays as 4 columns
set expandtab     " insert spaces when hitting TABs
set softtabstop=4 " insert/delete 4 spaces when hitting a TAB/BACKSPACE
set shiftround    " round indent to multiple of 'shiftwidth'
set autoindent    " align the new line indent with the previous line
```

**Comment by AFAgarap** [comment]
My bad, I don't have a `~/.vim_runtime/my_configs.vim`. I should have cleaned my `.vimrc`.

**Comment by airblade** [comment]
Since this has gone quiet and the plugin has changed quite a lot since this issue, I'm going to close it.  Please open a new issue if you have any further problems.  Thanks!

**Comment by AFAgarap** [comment]
@airblade I stopped using the plugin since it wasn't resolved at the time.
